### ISSUE TITLE
 great work! simple question about texture rendering

### ISSUE THREAD

**Issue by Holmes-Alan** [muelea/shapy#1]
Hello there, this is a really interesting work. I have been following your group for a while. You have several good works such VIBE, PARE, and SHAPY. My question is why there is no discussion on cloth rendering? Is it because it is a different topic than naked human digitalization or am I missing some obvious technique for texture rendering (clothes, skin and so on)?
I am looking forward to your reply. Thank you!

**Comment by muelea** [comment]
Our goal is to estimate SMPL-X parameters, especially body shape (betas). To properly use texture (from the image) we need to know the clothing. There is ongoing research in our department on that, e.g. [icon](https://github.com/yuliangxiu/icon). Currently, these are different problems we try to solve.
