### ISSUE TITLE
ModuleNotFoundError:  No module named 'mesh_mesh_intersect_cuda'

### ISSUE THREAD

**Issue by Mindusk** [muelea/shapy#16]
Hi.
I didn't find this file in the shapy folder.

**Comment by ijorquera** [comment]
Hello, I am having the same error, how did you manage to solve it? I tried reinstalling mesh-mesh-intersection but doesn't seem to have any errors on the installation log so I am a bit lost

**Comment by owais3901** [comment]
@ijorquera Hello, i am stuck at the same error can you share the solution? Thanks !!

**Comment by Sukruthi-C** [comment]
Hey you need CUDA. Then follow the instructions on the installation page. It creates mesh_mesh_cuda file.
