### ISSUE TITLE
Error when running Demo.py 

### ISSUE THREAD

**Issue by Daktha123** [muelea/shapy#24]
Hello, can someone help me with this error? I follow every step that mentions in the installation. But when I run the demo.py code, I got this error. Please check full error log in the attachment file. 

 File "/usr/local/lib/python3.10/dist-packages/omegaconf/nodes.py", line 29, in __init__
    self._set_value(value)  # lgtm [py/init-calls-subclass]
  File "/usr/local/lib/python3.10/dist-packages/omegaconf/nodes.py", line 46, in _set_value
    self._val = self.validate_and_convert(value)
  File "/usr/local/lib/python3.10/dist-packages/omegaconf/nodes.py", line 76, in validate_and_convert
    return self._validate_and_convert_impl(value)
  File "/usr/local/lib/python3.10/dist-packages/omegaconf/nodes.py", line 194, in _validate_and_convert_impl
    raise ValidationError("Cannot convert '$VALUE_TYPE' to string: '$VALUE'")
omegaconf.errors.ValidationError: Cannot convert 'tuple' to string: '('betas', 'global_rot', 'body_pose', 'camera')'
    full_key: groups[0]
    reference_type=Tuple[str]
    object_type=list
    
    
[error_log.txt](https://github.com/muelea/shapy/files/11498858/error_log.txt)

**Comment by muelea** [comment]
Hi, the error message (omegaconf.errors.ValidationError) suggests that your shell command is wrong. I assume you changed the demo command or have a typo in it. Can you check the command you're using?

**Comment by Daktha123** [comment]
I just followed every steps that you mention in github and I didn't change anything for the command. **Here is my google collab** :
https://colab.research.google.com/drive/1TlOPJ9X_LBVTRfnts-yoXwfaZcLGMrlb?usp=sharing  

Please check it on google collab and also if you have some video clips or tutorials or Colab notebook, please share it to me.

**Comment by muelea** [comment]
There is a lot of errors in the installation process in your colab example. The error message you're referring to is raised from omegaconf, so make sure you're using the correct version of omegaconf. But there is a couple of errors during the installation already which could cause error in demo.py as well. SHAPY and the demo code have been tested with Python 3.8, CUDA 10.2 and PyTorch 1.7.1 on Ubuntu 18.04. The Colab default is python 3.10 and CUDA 11.8, so I assume some packages are not compatible. If possible, try it on your computer with the tested configuration.

You can check the system defaults in Colab via:
```
!nvcc --version
!python --version
!cat /etc/os-release | head -n2
```

**Comment by Daktha123** [comment]
Thank you for getting back to me. It will be great if you provide me some video clip for tutorials. I got tooo many errors in the installation stage.

**Comment by muelea** [comment]
#12 Please see here for Colab.

**Comment by Kaustubh-1420** [comment]
> There is a lot of errors in the installation process in your colab example. The error message you're referring to is raised from omegaconf, so make sure you're using the correct version of omegaconf. But there is a couple of errors during the installation already which could cause error in demo.py as well. SHAPY and the demo code have been tested with Python 3.8, CUDA 10.2 and PyTorch 1.7.1 on Ubuntu 18.04. The Colab default is python 3.10 and CUDA 11.8, so I assume some packages are not compatible. If possible, try it on your computer with the tested configuration.
> 
> You can check the system defaults in Colab via:
> 
> ```
> !nvcc --version
> !python --version
> !cat /etc/os-release | head -n2
> ```

Hi, thanks for the clarification...
I tried running the Colab notebook, the official one, without making any changes and ran into several installation/build issues. Here’s what I encountered:

- Colab now uses Python 3.12, CUDA 12.6 (runtime only), and Torch 2.8.0, which are quite different from the tested setup (Python 3.8 + CUDA 10.2 + Torch 1.7.1).
- During installation, I get multiple build errors, mainly from:
- mesh_mesh_intersection → fails to build wheels (Could not build wheels for mesh_mesh_intersection)
- sklearn → metadata generation failed (since sklearn meta-package is deprecated; needs scikit-learn instead)
- As a result, demo.py fails to import modules dependent on the compiled extension.
