### ISSUE TITLE
ModuleNotFoundError: No module named 'attributes.attributes_betas'

### ISSUE THREAD

**Issue by msun67** [muelea/shapy#43]
I got this error while running demp.py in COLAB. Can you help me?

File "/usr/local/lib/python3.10/dist-packages/attributes/__init__.py", line 1, in <module>
    from .attributes_betas.a2b import A2B, A2BProbabilistic
ModuleNotFoundError: No module named 'attributes.attributes_betas'
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
[<ipython-input-30-1b7f6114e0a8>](https://localhost:8080/#) in <cell line: 1>()
----> 1 get_ipython().run_cell_magic('shell', '', 'cd /content/shapy/regressor\npython demo.py --save-vis true --save-params true --save-mesh true --split test --datasets openpose --output-folder samples/shapy_fit/ --exp-cfg configs/b2a_expose_hrnet_demo.yaml --exp-opts output_folder=../data/trained_models/shapy/SHAPY_A part_key=pose datasets.pose.openpose.data_folder=../samples datasets.pose.openpose.img_folder=images  datasets.pose.openpose.keyp_folder=openpose datasets.batch_size=1 datasets.pose_shape_ratio=1.0\n')

**Comment by Drexregion** [comment]
Hey where you able to solve this issue?
