### ISSUE TITLE
AttributeError: Caught AttributeError in DataLoader worker process 0.

### ISSUE THREAD

**Issue by msun67** [muelea/shapy#45]
Hi

Running this in a Colab Notebook.
All is well until running the demo.

I get:
 File "/usr/local/lib/python3.10/dist-packages/torch/_utils.py", line 722, in reraise
    raise exception
AttributeError: Caught AttributeError in DataLoader worker process 0.

Can you help me?

**Comment by Rut-B** [comment]
what is the cmd that you trying to run?

**Comment by msun67** [comment]
%%shell
cd /content/shapy/regressor
python demo.py --save-vis true --save-params true --save-mesh true --split test --datasets openpose --output-folder samples/shapy_fit/ --exp-cfg configs/b2a_expose_hrnet_demo.yaml --exp-opts output_folder=../data/trained_models/shapy/SHAPY_A part_key=pose datasets.pose.openpose.data_folder=../samples datasets.pose.openpose.img_folder=images  datasets.pose.openpose.keyp_folder=openpose datasets.batch_size=1 datasets.pose_shape_ratio=1.0


I am trying to run the cmd command.

**Comment by Rut-B** [comment]
this work for me: see
https://colab.research.google.com/drive/1vcMP4e8QALFUNzadKAz5fE7_3Gu90EDj#scrollTo=1naSpmZGIg_t

**Comment by msun67** [comment]
I can't see it because I don't have access to it :(

**Comment by Rut-B** [comment]
did you try to install pytorch ?

**Comment by msun67** [comment]
yes 
I have installed pytorch and torchvision

My error comes out like this
![SHAPY_Err](https://github.com/muelea/shapy/assets/83386842/f408bd44-a1cb-432e-97c5-c591f00355a9)

Can you help me :( ?

**Comment by muelea** [comment]
The error message says that np.int does not exist. I assume your install numpy version is different from the version we use in SHAPY. Make sure you have numpy==1.19.5 installed.

**Comment by msun67** [comment]
Thank you very much for your answer.

Is there a way to change the numpy version in colab?

i try:
!apt update
!pip install --upgrade pip setuptools wheel
!apt-get install -y libatlas-base-dev gfortran
!pip cache purge
!pip uninstall numpy

But installation of numpy==1.19.5 failed.
![SHAPY_Err2](https://github.com/muelea/shapy/assets/83386842/5ac22e76-2f5a-4285-9e38-920116300cd5)

**Comment by Drexregion** [comment]
> this work for me: see https://colab.research.google.com/drive/1vcMP4e8QALFUNzadKAz5fE7_3Gu90EDj#scrollTo=1naSpmZGIg_t

Hey is it possible for you to grant me access to the collab?

I am having some issues with mine.
