### ISSUE TITLE
Cannot import name 'BodyMeasurements' from 'body_measurements' 

### ISSUE THREAD

**Issue by chill781** [muelea/shapy#59]
I can't run the demo.py beacause the ImportError: cannot import name 'BodyMeasurements' from 'body_measurements' (unknown location). And I have checked the  body_measurements module,there is no such class  called 'BodyMeasuremnets'.Can somebody tell me how to solve this?

**Comment by chill781** [comment]
I figure this out,should install mesh-mesh-... first.

**Comment by Kaustubh-1420** [comment]
> I figure this out,should install mesh-mesh-... first.

Hi @chill781 , Were you able to successfully install mesh-mesh-intersection?
