### ISSUE TITLE
ModuleNotFoundError: No module named 'attributes.attributes_betas'

### ISSUE THREAD

**Issue by WenqiangX** [muelea/shapy#8]
Hi,

When I follow the installation instructions to finish the setup, and run the regressor demo. The terminal shows this error.
I think it is an issue of attributes installation.

Simply import attributes in python command environment will reproduce this error.

**Comment by WenqiangX** [comment]
it seems
export PYTHONPATH=$PYTHONPATH:$(pwd)/attributes/
can resolve this.

**Comment by Drexregion** [comment]
Hey I am still having the same problem and the above solution is not working for me can you recommend any help?

**Comment by Drexregion** [comment]
> it seems export PYTHONPATH=$PYTHONPATH:$(pwd)/attributes/ can resolve this.

Hey I am still having the same problem and the above solution is not working for me can you recommend any help?
